Fix AudioPluginInstance template constructor parameter type
The template constructor's parameter `const short channelLayoutList[numLayouts][2]`
decays to `const short (*)[2]` (pointer to array), which doesn't match any
AudioProcessor constructor.

Changed to `const short (&channelLayoutList)[numLayouts][2]` (reference to array)
to preserve the array type and match the AudioProcessor template constructor
that accepts `const short (&)[numLayouts][2]`.

This fixes the compilation error:
  error: no matching constructor for initialization of 'AudioProcessor'
  AudioPluginInstance (const short channelLayoutList[numLayouts][2])
    : AudioProcessor (channelLayoutList) {}